//
//  ISO3166_2.swift
//  Pods
//
//  Created by Zennon Jean S. Gosalvez on 2016-01-14.
//
//

open class ISO3166_2 {
    
    open static let subdivisionCodes = [
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-00",
            category: "region",
            name: "National Capital Region",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-01",
            category: "region",
            name: "Ilocos (Region I)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-02",
            category: "region",
            name: "Cagayan Valley (Region II)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-03",
            category: "region",
            name: "Central Luzon (Region III)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-05",
            category: "region",
            name: "Bicol (Region V)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-06",
            category: "region",
            name: "Western Visayas (Region VI)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-07",
            category: "region",
            name: "Central Visayas (Region VII)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-08",
            category: "region",
            name: "Eastern Visayas (Region VIII)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-09",
            category: "region",
            name: "Zamboanga Peninsula (Region IX)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-10",
            category: "region",
            name: "Northern Mindanao (Region X)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-11",
            category: "region",
            name: "Davao (Region XI)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-12",
            category: "region",
            name: "Soccsksargen (Region XII)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-13",
            category: "region",
            name: "Caraga (Region XIII)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-14",
            category: "region",
            name: "Autonomous Region in Muslim Mindanao (ARMM)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-15",
            category: "region",
            name: "Cordillera Administrative Region (CAR)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-40",
            category: "region",
            name: "Calabarzon (Region IV-A)",
            parentSubdivisionCode: nil),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-41",
            category: "region",
            name: "Mimaropa (Region IV-B)",
            parentSubdivisionCode: nil),
        
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ABR",
            category: "province",
            name: "Abra",
            parentSubdivisionCode: "PH-15"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-AGN",
            category: "province",
            name: "Agusan del Norte",
            parentSubdivisionCode: "PH-13"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-AGS",
            category: "province",
            name: "Agusan del Sur",
            parentSubdivisionCode: "PH-13"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-AKL",
            category: "province",
            name: "Aklan",
            parentSubdivisionCode: "PH-06"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ALB",
            category: "province",
            name: "Albay",
            parentSubdivisionCode: "PH-05"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ANT",
            category: "province",
            name: "Antique",
            parentSubdivisionCode: "PH-06"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-APA",
            category: "province",
            name: "Apayao",
            parentSubdivisionCode: "PH-15"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-AUR",
            category: "province",
            name: "Aurora",
            parentSubdivisionCode: "PH-03"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BAS",
            category: "province",
            name: "Basilan",
            parentSubdivisionCode: "PH-09"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BAN",
            category: "province",
            name: "Bataan",
            parentSubdivisionCode: "PH-03"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BTN",
            category: "province",
            name: "Batanes",
            parentSubdivisionCode: "PH-02"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BTG",
            category: "province",
            name: "Batangas",
            parentSubdivisionCode: "PH-40"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BEN",
            category: "province",
            name: "Benguet",
            parentSubdivisionCode: "PH-15"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BIL",
            category: "province",
            name: "Biliran",
            parentSubdivisionCode: "PH-08"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BOH",
            category: "province",
            name: "Bohol",
            parentSubdivisionCode: "PH-07"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BUK",
            category: "province",
            name: "Bukidnon",
            parentSubdivisionCode: "PH-10"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-BUL",
            category: "province",
            name: "Bulacan",
            parentSubdivisionCode: "PH-03"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-CAG",
            category: "province",
            name: "Cagayan",
            parentSubdivisionCode: "PH-02"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-CAN",
            category: "province",
            name: "Camarines Norte",
            parentSubdivisionCode: "PH-05"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-CAS",
            category: "province",
            name: "Camarines Sur",
            parentSubdivisionCode: "PH-05"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-CAM",
            category: "province",
            name: "Camiguin",
            parentSubdivisionCode: "PH-10"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-CAP",
            category: "province",
            name: "Capiz",
            parentSubdivisionCode: "PH-06"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-CAT",
            category: "province",
            name: "Catanduanes",
            parentSubdivisionCode: "PH-05"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-CAV",
            category: "province",
            name: "Cavite",
            parentSubdivisionCode: "PH-40"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-CEB",
            category: "province",
            name: "Cebu",
            parentSubdivisionCode: "PH-07"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-COM",
            category: "province",
            name: "Compostela Valley",
            parentSubdivisionCode: "PH-11"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-NCO",
            category: "province",
            name: "Cotabato",
            parentSubdivisionCode: "PH-12"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-DAV",
            category: "province",
            name: "Davao del Norte",
            parentSubdivisionCode: "PH-11"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-DAS",
            category: "province",
            name: "Davao del Sur",
            parentSubdivisionCode: "PH-11"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-DVO",
            category: "province",
            name: "Davao Occidental",
            parentSubdivisionCode: "PH-11"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-DAO",
            category: "province",
            name: "Davao Oriental",
            parentSubdivisionCode: "PH-11"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-DIN",
            category: "province",
            name: "Dinagat Islands",
            parentSubdivisionCode: "PH-13"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-EAS",
            category: "province",
            name: "Eastern Samar",
            parentSubdivisionCode: "PH-08"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-GUI",
            category: "province",
            name: "Guimaras",
            parentSubdivisionCode: "PH-06"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-IFU",
            category: "province",
            name: "Ifugao",
            parentSubdivisionCode: "PH-15"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ILN",
            category: "province",
            name: "Ilocos Norte",
            parentSubdivisionCode: "PH-01"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ILS",
            category: "province",
            name: "Ilocos Sur",
            parentSubdivisionCode: "PH-01"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ILI",
            category: "province",
            name: "Iloilo",
            parentSubdivisionCode: "PH-06"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ISA",
            category: "province",
            name: "Isabela",
            parentSubdivisionCode: "PH-02"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-KAL",
            category: "province",
            name: "Kalinga",
            parentSubdivisionCode: "PH-15"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-LAG",
            category: "province",
            name: "Laguna",
            parentSubdivisionCode: "PH-40"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-LAN",
            category: "province",
            name: "Lanao del Norte",
            parentSubdivisionCode: "PH-12"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-LAS",
            category: "province",
            name: "Lanao del Sur",
            parentSubdivisionCode: "PH-14"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-LUN",
            category: "province",
            name: "La Union",
            parentSubdivisionCode: "PH-01"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-LEY",
            category: "province",
            name: "Leyte",
            parentSubdivisionCode: "PH-08"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-MAG",
            category: "province",
            name: "Maguindanao",
            parentSubdivisionCode: "PH-14"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-MAD",
            category: "province",
            name: "Marinduque",
            parentSubdivisionCode: "PH-41"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-MAS",
            category: "province",
            name: "Masbate",
            parentSubdivisionCode: "PH-05"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-MDC",
            category: "province",
            name: "Mindoro Occidental",
            parentSubdivisionCode: "PH-41"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-MDR",
            category: "province",
            name: "Mindoro Oriental",
            parentSubdivisionCode: "PH-41"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-MSC",
            category: "province",
            name: "Misamis Occidental",
            parentSubdivisionCode: "PH-10"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-MSR",
            category: "province",
            name: "Misamis Oriental",
            parentSubdivisionCode: "PH-10"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-MOU",
            category: "province",
            name: "Mountain Province",
            parentSubdivisionCode: "PH-15"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-NEC",
            category: "province",
            name: "Negros Occidental",
            parentSubdivisionCode: "PH-06"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-NER",
            category: "province",
            name: "Negros Oriental",
            parentSubdivisionCode: "PH-07"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-NSA",
            category: "province",
            name: "Northern Samar",
            parentSubdivisionCode: "PH-08"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-NUE",
            category: "province",
            name: "Nueva Ecija",
            parentSubdivisionCode: "PH-03"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-NUV",
            category: "province",
            name: "Nueva Vizcaya",
            parentSubdivisionCode: "PH-02"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-PLW",
            category: "province",
            name: "Palawan",
            parentSubdivisionCode: "PH-41"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-PAM",
            category: "province",
            name: "Pampanga",
            parentSubdivisionCode: "PH-03"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-PAN",
            category: "province",
            name: "Pangasinan",
            parentSubdivisionCode: "PH-01"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-QUE",
            category: "province",
            name: "Quezon",
            parentSubdivisionCode: "PH-40"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-QUI",
            category: "province",
            name: "Quirino",
            parentSubdivisionCode: "PH-02"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-RIZ",
            category: "province",
            name: "Rizal",
            parentSubdivisionCode: "PH-40"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ROM",
            category: "province",
            name: "Romblon",
            parentSubdivisionCode: "PH-41"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-WSA",
            category: "province",
            name: "Samar",
            parentSubdivisionCode: "PH-08"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SAR",
            category: "province",
            name: "Sarangani",
            parentSubdivisionCode: "PH-11"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SIG",
            category: "province",
            name: "Siquijor",
            parentSubdivisionCode: "PH-07"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SOR",
            category: "province",
            name: "Sorsogon",
            parentSubdivisionCode: "PH-05"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SCO",
            category: "province",
            name: "South Cotabato",
            parentSubdivisionCode: "PH-11"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SLE",
            category: "province",
            name: "Southern Leyte",
            parentSubdivisionCode: "PH-08"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SUK",
            category: "province",
            name: "Sultan Kudarat",
            parentSubdivisionCode: "PH-12"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SLU",
            category: "province",
            name: "Sulu",
            parentSubdivisionCode: "PH-14"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SUN",
            category: "province",
            name: "Surigao del Norte",
            parentSubdivisionCode: "PH-13"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-SUR",
            category: "province",
            name: "Surigao del Sur",
            parentSubdivisionCode: "PH-13"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-TAR",
            category: "province",
            name: "Tarlac",
            parentSubdivisionCode: "PH-03"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-TAW",
            category: "province",
            name: "Tawi-Tawi",
            parentSubdivisionCode: "PH-14"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ZMB",
            category: "province",
            name: "Zambales",
            parentSubdivisionCode: "PH-03"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ZAN",
            category: "province",
            name: "Zamboanga del Norte",
            parentSubdivisionCode: "PH-09"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ZAS",
            category: "province",
            name: "Zamboanga del Sur",
            parentSubdivisionCode: "PH-09"),
        SubdivisionCode(ISO3166_1Alpha_2Code: "PH",
            code: "PH-ZSI",
            category: "province",
            name: "Zamboanga Sibugay",
            parentSubdivisionCode: "PH-09"),
    ]
    
    open class func subdivisionCodeFromCode(_ code: String) -> SubdivisionCode? {
        for subdivisionCode in subdivisionCodes {
            if subdivisionCode.code == code {
                return subdivisionCode
            }
        }
        
        return nil
    }
}
